included:
  - Source
  - Tests
excluded:
  - Dependencies
disabled_rules:
  - unused_optional_binding
  - file_header
  - no_extension_access_modifier
  - number_separator
  - object_literal
  - pattern_matching_keywords
  - private_over_fileprivate
  - strict_fileprivate
  - sorted_imports
  - identifier_name # Disabled due to a lot of one symbol identifiers
  # Temporary disabled
  - explicit_type_interface
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - function_parameter_count
  - force_unwrapping
  - explicit_top_level_acl
  - todo
  - implicitly_unwrapped_optional
  - attributes
  - force_cast
  - extension_access_modifier
  - large_tuple
  - no_grouping_extension
opt_in_rules:
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - colon
  - comma
  - compiler_protocol_init
  - conditional_returns_on_newline
  - control_statement
  - discarded_notification_center_observer
  - discouraged_direct_init
  - dynamic_inline
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_enum_raw_value
  - explicit_init
  - fatal_error_message
  - first_where
  - for_where
  - force_try
  - generic_type_name
  - identifier_name
  - implicit_getter
  - implicit_return
  - is_disjoint
  - joined_default_parameter
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_nsgeometry_functions
  - let_var_whitespace
  - mark
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - nesting
  - nimble_operator
  - notification_center_detachment
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - private_outlet
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_call
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - statement_position
  - superfluous_disable_command
  - switch_case_on_newline
  - syntactic_sugar
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - unused_enumerated
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_whitespace
  - void_return
  - weak_delegate
  - xctfail_message
  - legacy_constructor
  - type_name
force_cast: warning
shorthand_operator: warning
empty_count: warning
